version: 2.1
orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@1.0.0

jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Instalar dependências do sistema (Xvfb)
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb
      - run:
          name: Instalar Jest JUnit
          command: yarn add jest-junit --ignore-workspace-root-check
      - run:
          name: Rodar lint
          command: yarn lint
      - run:
          name: Rodar testes unitários
          command: yarn run jest --verbose --no-cache
          
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Rodar build
          command: yarn run build
      - store_artifacts:
          path: dist
          destination: node-build
          
  deploy:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run:
          name: Instalar Vercel CLI
          command: yarn global add vercel
      - run:
          name: Fazer Deploy no Vercel
          command: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN


  cypress-test:
    docker:
      - image: cypress/included:10.0.0
    steps:
      - checkout
      - run:
          name: Rodar testes E2E com Cypress
          command: yarn cy:run --headless
          
workflows:
  build-and-test-and-deploy:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
      - deploy:
          requires:
            - build-node
      - cypress-test:
          requires:
            - deploy
